server:
  port: 8888

app:
  api-prefix: /api/v1
  strip-prefix: 2 # cắt chữ /api/v1 để gọi /** vào endpoint service

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/** # Khi map prefix là identity thì sẽ route toàn bộ api về identity_service
          filters:
            - StripPrefix=${app.strip-prefix}
        - id: profile-service
          uri: http://localhost:8081
          predicates: # có thể gắn 2 path ứng với 2 endpoint nếu cần truy cập đến
            - Path=${app.api-prefix}/profile/users/** #, ${app.api-prefix}/profile/internal/users/**
          filters:
            - StripPrefix=${app.strip-prefix}
